"""High-level client for the hacienda-engine API.

`HaciendaClient` (sync) and `AsyncHaciendaClient` (async) each wrap the generated
`AuthenticatedClient` (`_generated/client.py`, httpx-based) and expose one
namespace attribute per OpenAPI tag (`client.pii.scan_text(...)`,
`client.documents.process_documents(...)`, `client.auth.get_whoami()`, ...) —
one namespace class per tag, generated mechanically from `_generated/api/`'s
module list so a new route picked up by the next `scripts/generate.sh` run gets
a namespace method automatically the next time this file is regenerated by hand
from the same introspection (see `sdks/python/README.md`).

Every namespace method routes through `_detailed` generated functions and
`errors._unwrap`, never the plain `sync`/`asyncio` convenience functions —
those collapse every non-2xx response (including documented 401/403/404/400)
into `None`, which would make an error indistinguishable from an empty success.
"""

from __future__ import annotations

import time
from typing import Any, Literal
from uuid import UUID

import httpx

from hacienda_sdk._generated.api.audit import get_audit, verify_audit
from hacienda_sdk._generated.api.auth import get_auth_config, get_whoami, issue_key, revoke_key
from hacienda_sdk._generated.api.compliance import get_compliance_dpia, get_compliance_report
from hacienda_sdk._generated.api.documents import process_documents, process_documents_async
from hacienda_sdk._generated.api.glossary import get_glossary
from hacienda_sdk._generated.api.info import get_health, get_info, get_version
from hacienda_sdk._generated.api.jobs import get_job, get_job_result, list_jobs
from hacienda_sdk._generated.api.pii import get_pii_config, redact_text, reveal_token, scan_text
from hacienda_sdk._generated.api.presets import (
    create_preset,
    delete_preset,
    get_preset,
    list_presets,
)
from hacienda_sdk._generated.api.rag import (
    answer,
    create_collection,
    delete_collection,
    get_collection,
    get_migrate_status,
    list_collections,
    list_documents,
    migrate_embeddings,
    retrieve,
    upsert_document,
)
from hacienda_sdk._generated.api.review import decide_review, get_review
from hacienda_sdk._generated.api.uploads import confirm_upload, presign_upload
from hacienda_sdk._generated.api.usage import get_usage
from hacienda_sdk._generated.api.versions import (
    diff_document,
    get_diff_job,
    get_document,
    list_document_versions,
)
from hacienda_sdk._generated.client import AuthenticatedClient
from hacienda_sdk._generated.models.answer_request import AnswerRequest
from hacienda_sdk._generated.models.confirm_upload_request import ConfirmUploadRequest
from hacienda_sdk._generated.models.create_preset_request import CreatePresetRequest
from hacienda_sdk._generated.models.issue_key_request import IssueKeyRequest
from hacienda_sdk._generated.models.migrate_embeddings_request import MigrateEmbeddingsRequest
from hacienda_sdk._generated.models.presign_upload_request import PresignUploadRequest
from hacienda_sdk._generated.models.process_documents_request import ProcessDocumentsRequest
from hacienda_sdk._generated.models.redact_text_request import RedactTextRequest
from hacienda_sdk._generated.models.reveal_token_request import RevealTokenRequest
from hacienda_sdk._generated.models.review_decide_request import ReviewDecideRequest
from hacienda_sdk._generated.models.scan_text_request import ScanTextRequest
from hacienda_sdk._generated.models.upsert_document_request import UpsertDocumentRequest
from hacienda_sdk._generated.types import UNSET, Unset
from hacienda_sdk.errors import _unwrap

# `target: "device"` (an embedded Cactus runtime, no HTTP underneath) is Phase 15
# of the platform-parity plan and not implemented yet. The literal is already a
# union of one so that phase can extend it without changing this signature.
Target = Literal["cloud"]

_DEFAULT_RETRY_STATUSES: frozenset[int] = frozenset({429, 502, 503, 504})
_RETRY_BACKOFF_BASE = 0.2


class _RetryTransport(httpx.BaseTransport):
    """Retries a request with exponential backoff on the configured status codes.

    Connection-level failures are httpx's own concern (handled by the wrapped
    transport); this only retries responses that completed but reported a
    transient-shaped status.
    """

    def __init__(
        self,
        transport: httpx.HTTPTransport,
        *,
        max_retries: int,
        retry_statuses: frozenset[int],
    ) -> None:
        self._transport = transport
        self._max_retries = max_retries
        self._retry_statuses = retry_statuses

    def handle_request(self, request: httpx.Request) -> httpx.Response:
        attempt = 0
        while True:
            response = self._transport.handle_request(request)
            if response.status_code not in self._retry_statuses or attempt >= self._max_retries:
                return response
            response.close()
            time.sleep(_RETRY_BACKOFF_BASE * (2**attempt))
            attempt += 1

    def close(self) -> None:
        self._transport.close()


class _AsyncRetryTransport(httpx.AsyncBaseTransport):
    def __init__(
        self,
        transport: httpx.AsyncHTTPTransport,
        *,
        max_retries: int,
        retry_statuses: frozenset[int],
    ) -> None:
        self._transport = transport
        self._max_retries = max_retries
        self._retry_statuses = retry_statuses

    async def handle_async_request(self, request: httpx.Request) -> httpx.Response:
        import asyncio

        attempt = 0
        while True:
            response = await self._transport.handle_async_request(request)
            if response.status_code not in self._retry_statuses or attempt >= self._max_retries:
                return response
            await response.aclose()
            await asyncio.sleep(_RETRY_BACKOFF_BASE * (2**attempt))
            attempt += 1

    async def aclose(self) -> None:
        await self._transport.aclose()


# ── Per-tag namespaces ──────────────────────────────────────────────────────
# Generated mechanically by introspecting `_generated/api/`'s `sync_detailed`/
# `asyncio_detailed` signatures — see this module's doc comment.


class _InfoNamespaceSync:
    def __init__(self, client):
        self._client = client

    def get_health(self):
        return _unwrap(get_health.sync_detailed(client=self._client))

    def get_info(self):
        return _unwrap(get_info.sync_detailed(client=self._client))

    def get_version(self):
        return _unwrap(get_version.sync_detailed(client=self._client))


class _InfoNamespaceAsync:
    def __init__(self, client):
        self._client = client

    async def get_health(self):
        return _unwrap(await get_health.asyncio_detailed(client=self._client))

    async def get_info(self):
        return _unwrap(await get_info.asyncio_detailed(client=self._client))

    async def get_version(self):
        return _unwrap(await get_version.asyncio_detailed(client=self._client))


class _DocumentsNamespaceSync:
    def __init__(self, client):
        self._client = client

    def process_documents(self, body: ProcessDocumentsRequest):
        return _unwrap(process_documents.sync_detailed(client=self._client, body=body))

    def process_documents_background(self, body: ProcessDocumentsRequest):
        return _unwrap(process_documents_async.sync_detailed(client=self._client, body=body))


class _DocumentsNamespaceAsync:
    def __init__(self, client):
        self._client = client

    async def process_documents(self, body: ProcessDocumentsRequest):
        return _unwrap(await process_documents.asyncio_detailed(client=self._client, body=body))

    async def process_documents_background(self, body: ProcessDocumentsRequest):
        return _unwrap(
            await process_documents_async.asyncio_detailed(client=self._client, body=body)
        )


class _PiiNamespaceSync:
    def __init__(self, client):
        self._client = client

    def get_pii_config(self):
        return _unwrap(get_pii_config.sync_detailed(client=self._client))

    def redact_text(self, body: RedactTextRequest):
        return _unwrap(redact_text.sync_detailed(client=self._client, body=body))

    def reveal_token(self, body: RevealTokenRequest):
        return _unwrap(reveal_token.sync_detailed(client=self._client, body=body))

    def scan_text(self, body: ScanTextRequest):
        return _unwrap(scan_text.sync_detailed(client=self._client, body=body))


class _PiiNamespaceAsync:
    def __init__(self, client):
        self._client = client

    async def get_pii_config(self):
        return _unwrap(await get_pii_config.asyncio_detailed(client=self._client))

    async def redact_text(self, body: RedactTextRequest):
        return _unwrap(await redact_text.asyncio_detailed(client=self._client, body=body))

    async def reveal_token(self, body: RevealTokenRequest):
        return _unwrap(await reveal_token.asyncio_detailed(client=self._client, body=body))

    async def scan_text(self, body: ScanTextRequest):
        return _unwrap(await scan_text.asyncio_detailed(client=self._client, body=body))


class _JobsNamespaceSync:
    def __init__(self, client):
        self._client = client

    def get_job(self, id: str):
        return _unwrap(get_job.sync_detailed(id, client=self._client))

    def get_job_result(self, id: str):
        return _unwrap(get_job_result.sync_detailed(id, client=self._client))

    def list_jobs(
        self, status: str | Unset = UNSET, limit: int | Unset = UNSET, offset: int | Unset = UNSET
    ):
        return _unwrap(
            list_jobs.sync_detailed(client=self._client, status=status, limit=limit, offset=offset)
        )


class _JobsNamespaceAsync:
    def __init__(self, client):
        self._client = client

    async def get_job(self, id: str):
        return _unwrap(await get_job.asyncio_detailed(id, client=self._client))

    async def get_job_result(self, id: str):
        return _unwrap(await get_job_result.asyncio_detailed(id, client=self._client))

    async def list_jobs(
        self, status: str | Unset = UNSET, limit: int | Unset = UNSET, offset: int | Unset = UNSET
    ):
        return _unwrap(
            await list_jobs.asyncio_detailed(
                client=self._client, status=status, limit=limit, offset=offset
            )
        )


class _AuditNamespaceSync:
    def __init__(self, client):
        self._client = client

    def get_audit(self):
        return _unwrap(get_audit.sync_detailed(client=self._client))

    def verify_audit(self):
        return _unwrap(verify_audit.sync_detailed(client=self._client))


class _AuditNamespaceAsync:
    def __init__(self, client):
        self._client = client

    async def get_audit(self):
        return _unwrap(await get_audit.asyncio_detailed(client=self._client))

    async def verify_audit(self):
        return _unwrap(await verify_audit.asyncio_detailed(client=self._client))


class _ReviewNamespaceSync:
    def __init__(self, client):
        self._client = client

    def decide_review(self, id: str, body: ReviewDecideRequest):
        return _unwrap(decide_review.sync_detailed(id, client=self._client, body=body))

    def get_review(self):
        return _unwrap(get_review.sync_detailed(client=self._client))


class _ReviewNamespaceAsync:
    def __init__(self, client):
        self._client = client

    async def decide_review(self, id: str, body: ReviewDecideRequest):
        return _unwrap(await decide_review.asyncio_detailed(id, client=self._client, body=body))

    async def get_review(self):
        return _unwrap(await get_review.asyncio_detailed(client=self._client))


class _ComplianceNamespaceSync:
    def __init__(self, client):
        self._client = client

    def get_compliance_dpia(self):
        return _unwrap(get_compliance_dpia.sync_detailed(client=self._client))

    def get_compliance_report(self):
        return _unwrap(get_compliance_report.sync_detailed(client=self._client))


class _ComplianceNamespaceAsync:
    def __init__(self, client):
        self._client = client

    async def get_compliance_dpia(self):
        return _unwrap(await get_compliance_dpia.asyncio_detailed(client=self._client))

    async def get_compliance_report(self):
        return _unwrap(await get_compliance_report.asyncio_detailed(client=self._client))


class _GlossaryNamespaceSync:
    def __init__(self, client):
        self._client = client

    def get_glossary(self):
        return _unwrap(get_glossary.sync_detailed(client=self._client))


class _GlossaryNamespaceAsync:
    def __init__(self, client):
        self._client = client

    async def get_glossary(self):
        return _unwrap(await get_glossary.asyncio_detailed(client=self._client))


class _AuthNamespaceSync:
    def __init__(self, client):
        self._client = client

    def get_auth_config(self):
        return _unwrap(get_auth_config.sync_detailed(client=self._client))

    def get_whoami(self):
        return _unwrap(get_whoami.sync_detailed(client=self._client))

    def issue_key(self, body: IssueKeyRequest):
        return _unwrap(issue_key.sync_detailed(client=self._client, body=body))

    def revoke_key(self, id: UUID):
        return _unwrap(revoke_key.sync_detailed(id, client=self._client))


class _AuthNamespaceAsync:
    def __init__(self, client):
        self._client = client

    async def get_auth_config(self):
        return _unwrap(await get_auth_config.asyncio_detailed(client=self._client))

    async def get_whoami(self):
        return _unwrap(await get_whoami.asyncio_detailed(client=self._client))

    async def issue_key(self, body: IssueKeyRequest):
        return _unwrap(await issue_key.asyncio_detailed(client=self._client, body=body))

    async def revoke_key(self, id: UUID):
        return _unwrap(await revoke_key.asyncio_detailed(id, client=self._client))


class _RagNamespaceSync:
    def __init__(self, client):
        self._client = client

    def answer(self, name: str, body: AnswerRequest):
        return _unwrap(answer.sync_detailed(name, client=self._client, body=body))

    def create_collection(self, body: Any):
        return _unwrap(create_collection.sync_detailed(client=self._client, body=body))

    def delete_collection(self, name: str):
        return _unwrap(delete_collection.sync_detailed(name, client=self._client))

    def get_collection(self, name: str):
        return _unwrap(get_collection.sync_detailed(name, client=self._client))

    def get_migrate_status(self, name: str, job_id: str):
        return _unwrap(get_migrate_status.sync_detailed(name, job_id, client=self._client))

    def list_collections(self, limit: int | Unset = UNSET, offset: int | Unset = UNSET):
        return _unwrap(
            list_collections.sync_detailed(client=self._client, limit=limit, offset=offset)
        )

    def list_documents(self, name: str, limit: int | Unset = UNSET, offset: int | Unset = UNSET):
        return _unwrap(
            list_documents.sync_detailed(name, client=self._client, limit=limit, offset=offset)
        )

    def migrate_embeddings(self, name: str, body: MigrateEmbeddingsRequest):
        return _unwrap(migrate_embeddings.sync_detailed(name, client=self._client, body=body))

    def retrieve(self, name: str, body: Any):
        return _unwrap(retrieve.sync_detailed(name, client=self._client, body=body))

    def upsert_document(self, name: str, body: UpsertDocumentRequest):
        return _unwrap(upsert_document.sync_detailed(name, client=self._client, body=body))


class _RagNamespaceAsync:
    def __init__(self, client):
        self._client = client

    async def answer(self, name: str, body: AnswerRequest):
        return _unwrap(await answer.asyncio_detailed(name, client=self._client, body=body))

    async def create_collection(self, body: Any):
        return _unwrap(await create_collection.asyncio_detailed(client=self._client, body=body))

    async def delete_collection(self, name: str):
        return _unwrap(await delete_collection.asyncio_detailed(name, client=self._client))

    async def get_collection(self, name: str):
        return _unwrap(await get_collection.asyncio_detailed(name, client=self._client))

    async def get_migrate_status(self, name: str, job_id: str):
        return _unwrap(await get_migrate_status.asyncio_detailed(name, job_id, client=self._client))

    async def list_collections(self, limit: int | Unset = UNSET, offset: int | Unset = UNSET):
        return _unwrap(
            await list_collections.asyncio_detailed(client=self._client, limit=limit, offset=offset)
        )

    async def list_documents(
        self, name: str, limit: int | Unset = UNSET, offset: int | Unset = UNSET
    ):
        return _unwrap(
            await list_documents.asyncio_detailed(
                name, client=self._client, limit=limit, offset=offset
            )
        )

    async def migrate_embeddings(self, name: str, body: MigrateEmbeddingsRequest):
        return _unwrap(
            await migrate_embeddings.asyncio_detailed(name, client=self._client, body=body)
        )

    async def retrieve(self, name: str, body: Any):
        return _unwrap(await retrieve.asyncio_detailed(name, client=self._client, body=body))

    async def upsert_document(self, name: str, body: UpsertDocumentRequest):
        return _unwrap(await upsert_document.asyncio_detailed(name, client=self._client, body=body))


class _PresetsNamespaceSync:
    def __init__(self, client):
        self._client = client

    def create_preset(self, body: CreatePresetRequest):
        return _unwrap(create_preset.sync_detailed(client=self._client, body=body))

    def delete_preset(self, id: UUID):
        return _unwrap(delete_preset.sync_detailed(id, client=self._client))

    def get_preset(self, id: UUID):
        return _unwrap(get_preset.sync_detailed(id, client=self._client))

    def list_presets(self):
        return _unwrap(list_presets.sync_detailed(client=self._client))


class _PresetsNamespaceAsync:
    def __init__(self, client):
        self._client = client

    async def create_preset(self, body: CreatePresetRequest):
        return _unwrap(await create_preset.asyncio_detailed(client=self._client, body=body))

    async def delete_preset(self, id: UUID):
        return _unwrap(await delete_preset.asyncio_detailed(id, client=self._client))

    async def get_preset(self, id: UUID):
        return _unwrap(await get_preset.asyncio_detailed(id, client=self._client))

    async def list_presets(self):
        return _unwrap(await list_presets.asyncio_detailed(client=self._client))


class _VersionsNamespaceSync:
    def __init__(self, client):
        self._client = client

    def diff_document(self, id: UUID, from_: int, to: int):
        return _unwrap(diff_document.sync_detailed(id, client=self._client, from_=from_, to=to))

    def get_diff_job(self, id: UUID, diff_job_id: str):
        return _unwrap(get_diff_job.sync_detailed(id, diff_job_id, client=self._client))

    def get_document(self, id: UUID):
        return _unwrap(get_document.sync_detailed(id, client=self._client))

    def list_document_versions(self, id: UUID):
        return _unwrap(list_document_versions.sync_detailed(id, client=self._client))


class _VersionsNamespaceAsync:
    def __init__(self, client):
        self._client = client

    async def diff_document(self, id: UUID, from_: int, to: int):
        return _unwrap(
            await diff_document.asyncio_detailed(id, client=self._client, from_=from_, to=to)
        )

    async def get_diff_job(self, id: UUID, diff_job_id: str):
        return _unwrap(await get_diff_job.asyncio_detailed(id, diff_job_id, client=self._client))

    async def get_document(self, id: UUID):
        return _unwrap(await get_document.asyncio_detailed(id, client=self._client))

    async def list_document_versions(self, id: UUID):
        return _unwrap(await list_document_versions.asyncio_detailed(id, client=self._client))


class _UploadsNamespaceSync:
    def __init__(self, client):
        self._client = client

    def confirm_upload(self, body: ConfirmUploadRequest):
        return _unwrap(confirm_upload.sync_detailed(client=self._client, body=body))

    def presign_upload(self, body: PresignUploadRequest):
        return _unwrap(presign_upload.sync_detailed(client=self._client, body=body))


class _UploadsNamespaceAsync:
    def __init__(self, client):
        self._client = client

    async def confirm_upload(self, body: ConfirmUploadRequest):
        return _unwrap(await confirm_upload.asyncio_detailed(client=self._client, body=body))

    async def presign_upload(self, body: PresignUploadRequest):
        return _unwrap(await presign_upload.asyncio_detailed(client=self._client, body=body))


class _UsageNamespaceSync:
    def __init__(self, client):
        self._client = client

    def get_usage(self, since: str | Unset = UNSET, until: str | Unset = UNSET):
        return _unwrap(get_usage.sync_detailed(client=self._client, since=since, until=until))


class _UsageNamespaceAsync:
    def __init__(self, client):
        self._client = client

    async def get_usage(self, since: str | Unset = UNSET, until: str | Unset = UNSET):
        return _unwrap(
            await get_usage.asyncio_detailed(client=self._client, since=since, until=until)
        )


# ── Top-level clients ────────────────────────────────────────────────────────


class HaciendaClient:
    """Synchronous client. One namespace attribute per OpenAPI tag."""

    def __init__(
        self,
        base_url: str,
        api_key: str,
        *,
        target: Target = "cloud",
        timeout: float = 30.0,
        max_retries: int = 2,
        retry_statuses: frozenset[int] = _DEFAULT_RETRY_STATUSES,
        verify_ssl: bool | str = True,
    ) -> None:
        if target != "cloud":
            raise ValueError(f'unsupported target {target!r} — only "cloud" is implemented today')

        transport = _RetryTransport(
            httpx.HTTPTransport(verify=verify_ssl),
            max_retries=max_retries,
            retry_statuses=retry_statuses,
        )
        self._client = AuthenticatedClient(
            base_url=base_url,
            token=api_key,
            timeout=httpx.Timeout(timeout),
            verify_ssl=verify_ssl,
            httpx_args={"transport": transport},
        )
        self.info = _InfoNamespaceSync(self._client)
        self.documents = _DocumentsNamespaceSync(self._client)
        self.pii = _PiiNamespaceSync(self._client)
        self.jobs = _JobsNamespaceSync(self._client)
        self.audit = _AuditNamespaceSync(self._client)
        self.review = _ReviewNamespaceSync(self._client)
        self.compliance = _ComplianceNamespaceSync(self._client)
        self.glossary = _GlossaryNamespaceSync(self._client)
        self.auth = _AuthNamespaceSync(self._client)
        self.rag = _RagNamespaceSync(self._client)
        self.presets = _PresetsNamespaceSync(self._client)
        self.versions = _VersionsNamespaceSync(self._client)
        self.uploads = _UploadsNamespaceSync(self._client)
        self.usage = _UsageNamespaceSync(self._client)

    def whoami(self):
        """`GET /v1/auth/whoami` — the calling key's own granted capabilities.

        The capability probe a client should use to decide which methods will
        actually work against the supplied key, since hacienda has one tier
        (unlike xberg's `_resolve_tier`, which this replaces): see
        `hacienda-api/src/handlers/auth.rs`'s `whoami` doc comment.
        """
        return self.auth.get_whoami()

    def close(self) -> None:
        self._client.get_httpx_client().close()

    def __enter__(self) -> HaciendaClient:
        return self

    def __exit__(self, *args: object) -> None:
        self.close()


class AsyncHaciendaClient:
    """Async twin of [`HaciendaClient`][hacienda_sdk.client.HaciendaClient] — same
    namespace attributes, every method a coroutine."""

    def __init__(
        self,
        base_url: str,
        api_key: str,
        *,
        target: Target = "cloud",
        timeout: float = 30.0,
        max_retries: int = 2,
        retry_statuses: frozenset[int] = _DEFAULT_RETRY_STATUSES,
        verify_ssl: bool | str = True,
    ) -> None:
        if target != "cloud":
            raise ValueError(f'unsupported target {target!r} — only "cloud" is implemented today')

        transport = _AsyncRetryTransport(
            httpx.AsyncHTTPTransport(verify=verify_ssl),
            max_retries=max_retries,
            retry_statuses=retry_statuses,
        )
        self._client = AuthenticatedClient(
            base_url=base_url,
            token=api_key,
            timeout=httpx.Timeout(timeout),
            verify_ssl=verify_ssl,
            httpx_args={"transport": transport},
        )
        self.info = _InfoNamespaceAsync(self._client)
        self.documents = _DocumentsNamespaceAsync(self._client)
        self.pii = _PiiNamespaceAsync(self._client)
        self.jobs = _JobsNamespaceAsync(self._client)
        self.audit = _AuditNamespaceAsync(self._client)
        self.review = _ReviewNamespaceAsync(self._client)
        self.compliance = _ComplianceNamespaceAsync(self._client)
        self.glossary = _GlossaryNamespaceAsync(self._client)
        self.auth = _AuthNamespaceAsync(self._client)
        self.rag = _RagNamespaceAsync(self._client)
        self.presets = _PresetsNamespaceAsync(self._client)
        self.versions = _VersionsNamespaceAsync(self._client)
        self.uploads = _UploadsNamespaceAsync(self._client)
        self.usage = _UsageNamespaceAsync(self._client)

    async def whoami(self):
        """`GET /v1/auth/whoami` — async twin of `HaciendaClient.whoami`."""
        return await self.auth.get_whoami()

    async def close(self) -> None:
        await self._client.get_async_httpx_client().aclose()

    async def __aenter__(self) -> AsyncHaciendaClient:
        return self

    async def __aexit__(self, *args: object) -> None:
        await self.close()
