apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hacienda-api
  namespace: hacienda-prod
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: hacienda-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - hacienda-prod
