//! Regulatory control checklists mapping articles to the controls that satisfy them.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
/// ComplianceChecklist struct
pub struct ComplianceChecklist {
    /// gdpr_articles field
    pub gdpr_articles: Vec<ChecklistItem>,
    /// ai_act_articles field
    pub ai_act_articles: Vec<ChecklistItem>,
    /// dora_articles field
    pub dora_articles: Vec<ChecklistItem>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
/// ChecklistItem struct
pub struct ChecklistItem {
    /// article field
    pub article: String,
    /// description field
    pub description: String,
    /// status field
    pub status: ControlStatus,
    /// The control in this pipeline that evidences the article.
    pub evidence: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
/// ControlStatus enum
pub enum ControlStatus {
    /// Implemented variant
    Implemented,
    /// Partial variant
    Partial,
    /// NotImplemented variant
    NotImplemented,
}

fn item(article: &str, description: &str, status: ControlStatus, evidence: &str) -> ChecklistItem {
    ChecklistItem {
        article: article.into(),
        description: description.into(),
        status,
        evidence: evidence.into(),
    }
}

/// Build the checklist for the controls this pipeline actually implements.
///
/// Status reflects what the code does, not an aspiration: articles covered by a
/// concrete module are `Implemented`, articles that need organisational process on
/// top of a generated artefact are `Partial`.
pub fn generate_checklist() -> ComplianceChecklist {
    use ControlStatus::{Implemented, Partial};

    ComplianceChecklist {
        gdpr_articles: vec![
            item(
                "Art. 5",
                "Principles relating to processing of personal data",
                Implemented,
                "Detection is local and span-scoped; audit records store blake3 digests, never raw spans",
            ),
            item(
                "Art. 25",
                "Data protection by design and by default",
                Implemented,
                "Redaction runs as a post-processor on every extraction (crate::redaction)",
            ),
            item(
                "Art. 32",
                "Security of processing",
                Implemented,
                "Tamper-evident audit chain with blake3 verification (crate::audit::AuditChain)",
            ),
            item(
                "Art. 33-34",
                "Personal data breach notification",
                Partial,
                "DORA incident report generator (crate::compliance::dora); notification process is organisational",
            ),
            item(
                "Art. 35",
                "Data protection impact assessment",
                Partial,
                "DPIA generated by crate::compliance::dpia; requires DPO sign-off",
            ),
        ],
        ai_act_articles: vec![
            item(
                "Art. 9",
                "Risk management system",
                Partial,
                "Risk register generated in the DPIA; ongoing review is organisational",
            ),
            item(
                "Art. 11",
                "Technical documentation",
                Implemented,
                "Model card generated by crate::compliance::model_card",
            ),
            item(
                "Art. 12",
                "Record-keeping",
                Implemented,
                "Append-only audit chain over every redaction (crate::audit)",
            ),
            item(
                "Art. 14",
                "Human oversight",
                Implemented,
                "Low-confidence detections routed to crate::review::ReviewQueue",
            ),
        ],
        dora_articles: vec![
            item(
                "Art. 5",
                "ICT risk management framework",
                Partial,
                "Risk assessment section of the generated DPIA",
            ),
            item(
                "Art. 19",
                "Reporting of major ICT-related incidents",
                Implemented,
                "crate::compliance::dora::generate_report produces a submission-shaped report",
            ),
        ],
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn should_cover_all_three_regulations() {
        let checklist = generate_checklist();
        assert!(!checklist.gdpr_articles.is_empty());
        assert!(!checklist.ai_act_articles.is_empty());
        assert!(!checklist.dora_articles.is_empty());
    }

    #[test]
    fn should_give_every_item_an_article_and_evidence() {
        let checklist = generate_checklist();
        let all = checklist
            .gdpr_articles
            .iter()
            .chain(&checklist.ai_act_articles)
            .chain(&checklist.dora_articles);
        for entry in all {
            assert!(
                entry.article.starts_with("Art."),
                "bad article: {}",
                entry.article
            );
            assert!(
                !entry.evidence.is_empty(),
                "{} has no evidence",
                entry.article
            );
        }
    }

    #[test]
    fn should_claim_human_oversight_only_because_a_review_queue_exists() {
        let checklist = generate_checklist();
        let art14 = checklist
            .ai_act_articles
            .iter()
            .find(|i| i.article == "Art. 14")
            .expect("AI Act Art. 14 is listed");
        assert_eq!(art14.status, ControlStatus::Implemented);
        assert!(art14.evidence.contains("ReviewQueue"));
    }
}
